# Generated by Django 5.2.4 on 2025-07-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apichatbot', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_date',
        ),
    ]
