# Generated by Django 5.2.4 on 2025-07-21 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apichatbot', '0003_remove_chatsession_deleted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_name',
            field=models.CharField(blank=True, default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True), max_length=255),
        ),
    ]
