# Generated by Django 5.2.4 on 2025-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apichatbot', '0004_alter_chatsession_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
