# Generated by Django 5.2.4 on 2025-08-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apichatbot', '0005_alter_chatsession_session_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_date']},
        ),
    ]
